import React from 'react';
import { jsPDF } from 'jspdf';

export default function ExportButton({ reviewData }) {
  const handleExport = () => {
    if (!reviewData) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    const addLine = (text, x, size, style = 'normal', rgb = [200, 200, 200]) => {
      doc.setFontSize(size);
      doc.setFont('courier', style);
      doc.setTextColor(...rgb);
      const lines = doc.splitTextToSize(String(text), pageWidth - x - 20);
      for (const line of lines) {
        if (y > 278) { doc.addPage(); y = 20; doc.setFillColor(8, 8, 8); doc.rect(0, 0, pageWidth, 300, 'F'); }
        doc.text(line, x, y);
        y += size * 0.52;
      }
    };

    // Black background
    doc.setFillColor(8, 8, 8);
    doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), 'F');

    addLine('V0IDCH3CK — CODE REVIEW REPORT', 15, 14, 'bold', [170, 255, 0]);
    y += 4;
    addLine(`HEALTH SCORE: ${reviewData.healthScore} / 100`, 15, 12, 'bold', [245, 245, 245]);
    y += 6;

    addLine('SUMMARY', 15, 10, 'bold', [85, 85, 85]);
    y += 2;
    addLine(reviewData.summary || '', 15, 9, 'normal', [136, 136, 136]);
    y += 6;

    if (reviewData.issues?.length) {
      addLine(`ISSUES (${reviewData.issues.length})`, 15, 10, 'bold', [85, 85, 85]);
      y += 2;
      reviewData.issues.forEach((issue, i) => {
        const typeMap = { bug: '[BUG]', security: '[SEC]', smell: '[WARN]', suggestion: '[INFO]' };
        const sevRgb = issue.severity === 'high' ? [255, 68, 68] : issue.severity === 'medium' ? [136, 136, 136] : [42, 42, 42];
        addLine(`${typeMap[issue.type] || '[INFO]'} ${issue.title}${issue.line ? ` — LINE ${issue.line}` : ''}`, 18, 9, 'bold', sevRgb);
        addLine(issue.description, 20, 8, 'normal', [100, 100, 100]);
        if (issue.fix) addLine(`FIX: ${issue.fix}`, 20, 8, 'italic', [80, 120, 80]);
        y += 2;
      });
    }

    if (reviewData.positives?.length) {
      y += 2;
      addLine('POSITIVES', 15, 10, 'bold', [85, 85, 85]);
      y += 2;
      reviewData.positives.forEach(p => addLine(`+ ${p}`, 18, 9, 'normal', [100, 140, 80]));
    }

    if (reviewData.metrics) {
      y += 4;
      addLine('METRICS', 15, 10, 'bold', [85, 85, 85]);
      y += 2;
      Object.entries(reviewData.metrics).forEach(([k, v]) => {
        addLine(`${k.toUpperCase().padEnd(14)} ${String(v).toUpperCase()}`, 18, 9, 'normal', [136, 136, 136]);
      });
    }

    y += 8;
    addLine(`Generated by V0idCh3ck  ${new Date().toLocaleDateString()}`, 15, 7, 'italic', [50, 50, 50]);

    doc.save('v0idch3ck-report.pdf');
  };

  return (
    <button
      className="btn-secondary"
      onClick={handleExport}
      disabled={!reviewData}
      title={!reviewData ? 'Run a review first' : 'Export as PDF'}
    >
      Export PDF
    </button>
  );
}