const terminalNoirTheme = {
    base: 'vs-dark',
    inherit: false,
    rules: [
        { token: '', foreground: '888888', background: '080808' },
        { token: 'comment', foreground: '2A2A2A', fontStyle: 'italic' },
        { token: 'comment.line', foreground: '2A2A2A', fontStyle: 'italic' },
        { token: 'comment.block', foreground: '2A2A2A', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'F5F5F5', fontStyle: 'bold' },
        { token: 'keyword.control', foreground: 'F5F5F5', fontStyle: 'bold' },
        { token: 'keyword.operator', foreground: '666666' },
        { token: 'string', foreground: '777777' },
        { token: 'string.escape', foreground: '666666' },
        { token: 'number', foreground: 'AAAAAA' },
        { token: 'regexp', foreground: '888888' },
        { token: 'type', foreground: 'CCCCCC', fontStyle: 'bold' },
        { token: 'type.identifier', foreground: 'CCCCCC' },
        { token: 'class', foreground: 'F5F5F5', fontStyle: 'bold' },
        { token: 'function', foreground: 'DDDDDD' },
        { token: 'variable', foreground: 'AAAAAA' },
        { token: 'variable.predefined', foreground: '888888' },
        { token: 'variable.parameter', foreground: '999999' },
        { token: 'operator', foreground: '555555' },
        { token: 'delimiter', foreground: '444444' },
        { token: 'delimiter.bracket', foreground: '555555' },
        { token: 'delimiter.curly', foreground: '555555' },
        { token: 'delimiter.parenthesis', foreground: '555555' },
        { token: 'tag', foreground: 'CCCCCC' },
        { token: 'tag.id', foreground: 'F5F5F5' },
        { token: 'attribute.name', foreground: '999999' },
        { token: 'attribute.value', foreground: '777777' },
        { token: 'identifier', foreground: 'AAAAAA' },
        { token: 'constant', foreground: 'CCCCCC' },
        { token: 'namespace', foreground: 'BBBBBB' },
        { token: 'metatag', foreground: '555555' },
        { token: 'annotation', foreground: '666666' },
        { token: 'invalid', foreground: 'FF4444', fontStyle: 'underline' },
    ],
    colors: {
        'editor.background': '#080808',
        'editor.foreground': '#888888',
        'editor.lineHighlightBackground': '#0F0F0F',
        'editor.lineHighlightBorder': '#0F0F0F',
        'editor.selectionBackground': '#1E1E1E',
        'editor.inactiveSelectionBackground': '#161616',
        'editor.selectionHighlightBackground': '#161616',
        'editorLineNumber.foreground': '#222222',
        'editorLineNumber.activeForeground': '#444444',
        'editorCursor.foreground': '#AAFF00',
        'editorCursor.background': '#080808',
        'editorIndentGuide.background': '#111111',
        'editorIndentGuide.activeBackground': '#1A1A1A',
        'editorWhitespace.foreground': '#111111',
        'editorBracketMatch.background': '#1A1A1A',
        'editorBracketMatch.border': '#333333',
        'editorWidget.background': '#0D0D0D',
        'editorWidget.border': '#1A1A1A',
        'editorSuggestWidget.background': '#0D0D0D',
        'editorSuggestWidget.border': '#1A1A1A',
        'editorSuggestWidget.foreground': '#888888',
        'editorSuggestWidget.selectedBackground': '#1A1A1A',
        'editorSuggestWidget.highlightForeground': '#F5F5F5',
        'editorHoverWidget.background': '#0D0D0D',
        'editorHoverWidget.border': '#1A1A1A',
        'scrollbar.shadow': '#00000000',
        'scrollbarSlider.background': '#1A1A1A',
        'scrollbarSlider.hoverBackground': '#222222',
        'scrollbarSlider.activeBackground': '#2A2A2A',
        'focusBorder': '#AAFF0033',
        'editor.findMatchBackground': '#AAFF0022',
        'editor.findMatchHighlightBackground': '#AAFF0011',
    },
};

export default terminalNoirTheme;